version: '3'
services:
  rancher:
    image: "rancher/rancher:stable"
    container_name: "rancher"
    hostname: "rancher"
    restart: unless-stopped
    privileged: true
    ports:
      - 80
      - 443
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.rancher.entrypoints=web"
      - "traefik.http.routers.rancher.rule=Host(`rancher.domain.example`)"
      - "traefik.http.routers.rancher.service=rancher"
      - "traefik.http.services.rancher.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.rancher.middlewares=redirect-to-https"
      # https
      - "traefik.http.routers.rancher-secure.entrypoints=websecure"
      - "traefik.http.routers.rancher-secure.rule=Host(`rancher.domain.example`)"
      - "traefik.http.services.rancher-secure.loadbalancer.server.port=443"
      - "traefik.http.routers.rancher-secure.service=rancher"
      - "traefik.http.routers.rancher-secure.tls=true"
      - "traefik.http.routers.rancher-secure.tls.certResolver=letsencrypt-prod"
      - "traefik.http.routers.rancher-secure.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    volumes:
      - "./rancher/data:/var/lib/rancher:rw"
  headscale:
    image: "headscale/headscale"
    container_name: "headscale"
    hostname: "headscale"
    restart: unless-stopped
    ports:
      - 443
      - 9090
      - "3478:3478/udp"
    labels:
      - "traefik.enable=true"
      # for headscale main port and derp
      - "traefik.tcp.routers.headscale.entrypoints=websecure"
      - "traefik.tcp.routers.headscale.tls.passthrough=true"
      - "traefik.tcp.routers.headscale.rule=HostSNI(`headscale.domain.example`)"
      - "traefik.tcp.services.headscale.loadbalancer.server.port=443"
      # for headscale metrics api
      - "traefik.http.routers.headscale-metrics.entrypoints=websecure"
      - "traefik.http.routers.headscale-metrics.rule=Host(`metrics.headscale.domain.example`)"
      - "traefik.http.services.headscale-metrics.loadbalancer.server.port=9090"
    volumes:
      - "./headscale/config:/etc/headscale/:ro"
      - "./headscale/data:/var/lib/headscale:rw"
    command:
      - "headscale"
      - "serve"
  traefik:
    image: "traefik"
    container_name: "traefik"
    hostname: "traefik"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "./traefik/acme_prod.json:/acme_prod.json:rw"
      - "./traefik/acme_stag.json:/acme_stag.json:rw"
      - "./traefik/traefik.yaml:/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      

networks:
  default: {}