## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt-prod:
    acme:
      #caServer: https://acme-v02.api.letsencrypt.org/directory
      email: example@gmail.com
      storage: /acme_prod.json
      httpChallenge:
        entryPoint: web
  letsencrypt-stag:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: example@gmail.com
      storage: /acme_stag.json
      httpChallenge:
        entryPoint: web